from django.db import models


class Transformer(models.Model):
    Manufacturer_name = models.CharField(max_length=200)
    Transformer_location_name = models.CharField(max_length=200)
    Transformer_number = models.CharField(max_length=100, primary_key=True)
    Meter_number = models.CharField(max_length=100)
    Manufacturer_Serial_number = models.CharField(max_length=200, null=True)
    Section = models.CharField(max_length=200, null=True)
    Sub_Division = models.CharField(max_length=200, null=True)
    Division = models.CharField(max_length=200, null=True)
    Circle = models.CharField(max_length=200, null=True)
    Region = models.CharField(max_length=200, null=True)
    Latitude = models.CharField(max_length=200, null=True)
    Longitude = models.CharField(max_length=200, null=True)
    Status = models.CharField(max_length=200, null=True)
    Transformers_Name_plate = models.CharField(max_length=200, null=True)
    KVA = models.IntegerField()
    Volts_H_V = models.IntegerField()
    Volts_L_V = models.IntegerField()
    Amperes_H_V = models.IntegerField()
    Amperes_L_V = models.IntegerField()
    Phases_HV = models.IntegerField()
    Phases_LV = models.IntegerField()
    Type_of_Cooling = models.CharField(max_length=200, null=True)
    Frequency = models.IntegerField(null=True)
    Impedance_volts = models.CharField(max_length=200, null=True)
    Connection_symbols = models.CharField(max_length=200, null=True)
    Core_and_winding = models.CharField(max_length=200, null=True)
    Total_weight = models.CharField(max_length=200, null=True)
    Oil = models.CharField(max_length=200, null=True)
    Year_of_manufacturer = models.DateTimeField(null=True)


class Events(models.Model):
    # id = models.AutoField()
    mainId = models.ForeignKey(Transformer, on_delete=models.CASCADE)
    Time_Stamp = models.DateTimeField(primary_key=True)
    V_R = models.IntegerField(null=True)
    V_Y = models.IntegerField(null=True)
    V_B = models.IntegerField(null=True)
    VRB = models.IntegerField(null=True)
    VRY = models.IntegerField(null=True)
    VYB = models.IntegerField(null=True)
    I_R = models.IntegerField(null=True)
    I_Y = models.IntegerField(null=True)
    I_B = models.IntegerField(null=True)
    kW = models.IntegerField(null=True)
    kVA = models.IntegerField(null=True)
    PF_R = models.IntegerField(null=True)
    PF_Y = models.IntegerField(null=True)
    PF_B = models.IntegerField(null=True)
    THD_V_R = models.IntegerField(null=True)
    THD_V_Y = models.IntegerField(null=True)
    THD_V_B = models.IntegerField(null=True)
    THD_I_R = models.IntegerField(null=True)
    THD_I_Y = models.IntegerField(null=True)
    THD_I_B = models.IntegerField(null=True)
    FREQUENCY = models.IntegerField(null=True)
    Frwd_kWh = models.IntegerField(null=True)
    REV_ACTENERGY = models.IntegerField(null=True)
    FRWD_APPENERGY = models.IntegerField(null=True)
    FRWD_REACTENERGY = models.IntegerField(null=True)
    kVA_R = models.IntegerField(null=True)
    kVA_Y = models.IntegerField(null=True)
    kVA_B = models.IntegerField(null=True)
    KVAH_FWD = models.IntegerField(null=True)
    KVAH_REV = models.IntegerField(null=True)
    kVAr_R = models.IntegerField(null=True)
    KVARH_LAG_FWD = models.IntegerField(null=True)
    KVARH_LAG_REV = models.IntegerField(null=True)
    KVARH_LEAD_FWD = models.IntegerField(null=True)
    KVARH_LEAD_REV = models.IntegerField(null=True)
    kVAr_Y = models.IntegerField(null=True)
    kVAr_B = models.IntegerField(null=True)
    kWH_Fwd = models.IntegerField(null=True)
    KWH_REV = models.IntegerField(null=True)
    kW_R = models.IntegerField(null=True)
    kW_Y = models.IntegerField(null=True)
    kW_B = models.IntegerField(null=True)
    kVA_1 = models.IntegerField(null=True)
    REV_APPENERGY = models.IntegerField(null=True)
    REV_REACTENERGY = models.IntegerField(null=True)
    TOT_kVAh = models.IntegerField(null=True)
    TOT_KVARH_LEG = models.IntegerField(null=True)
    TOT_kWh_Fwd_kWh_Active_Energy_Sent_Out = models.IntegerField(null=True)
    Unnamed_column1 = models.IntegerField(null=True)
    TEMP4 = models.IntegerField(null=True)
    TOT_KVAH_1 = models.IntegerField(null=True)
    TOT_KVARH_LEG = models.IntegerField(null=True)
    TOT_KWH = models.IntegerField(null=True)
