# Generated by Django 4.1.1 on 2022-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='Frequency',
            field=models.IntegerField(null=True),
        ),
    ]
